//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonefyWeb.DistributedServices.WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonefyWeb.DistributedServices.WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account_Id no puede estar vacío.
        /// </summary>
        internal static string AccountIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount debe ser mayor que 0.
        /// </summary>
        internal static string AmountMustBeGreatherThan0 {
            get {
                return ResourceManager.GetString("AmountMustBeGreatherThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CategoryType debe ser mayor que 0.
        /// </summary>
        internal static string CategoryTypeMustBeGreatherThan0 {
            get {
                return ResourceManager.GetString("CategoryTypeMustBeGreatherThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concept no puede estar vacío.
        /// </summary>
        internal static string ConceptCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConceptCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del nombre debe estar entre 2 y 50 caracteres.
        /// </summary>
        internal static string LenghtMustBeInto2To50 {
            get {
                return ResourceManager.GetString("LenghtMustBeInto2To50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede estar vacío.
        /// </summary>
        internal static string NameCannotBeNull {
            get {
                return ResourceManager.GetString("NameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PaymentMethod no es un valor válido.
        /// </summary>
        internal static string PaymentMethodNeedsValidValue {
            get {
                return ResourceManager.GetString("PaymentMethodNeedsValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El icono no puede estar vacío.
        /// </summary>
        internal static string TheIconCannotBeEmpty {
            get {
                return ResourceManager.GetString("TheIconCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type no es un valor válido.
        /// </summary>
        internal static string TypeNeedsValidValue {
            get {
                return ResourceManager.GetString("TypeNeedsValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no puede estar vacío.
        /// </summary>
        internal static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor debe ser mayor que 0.
        /// </summary>
        internal static string ValueMustBeGreatherThan0 {
            get {
                return ResourceManager.GetString("ValueMustBeGreatherThan0", resourceCulture);
            }
        }
    }
}
